###
POST http://localhost:9000/api/empleados HTTP/1.1
Content-Type: application/json

{
    "nombre": "Daniela",
    "apellidos": "riascos",
    "dependencia": "Salud",
    "salario": 5000000
}

###
GET http://localhost:9000/api/empleados HTTP/1.1


###
GET http://localhost:9000/api/empleados/6431088d0e52a238930e2ae9  HTTP/1.1

###

PUT http://localhost:9000/api/empleados/643182fe2e3c43d689210751 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luz Marina",
    "apellidos": "Pedroza",
    "dependencia": "Juridica",
    "salario": 4000000
}


###
DELETE http://localhost:9000/api/empleados/643182fe2e3c43d689210751  HTTP/1.1